### ISSUE TITLE
Sketchup is only accepting the files with extension ".skp" and NOT ".SKP"

### ISSUE THREAD

**Issue by vineeshvs** [sparkfun/3D_Models#147]
I think there is an issue as mentioned in the title. Please rename all ".SKP" extensions with ".skp" if that's the case.

The models are excellent. Really helped us

**Comment by ToniCorinne** [comment]
Sorry to hear you're having issues with the models! We'll take a look and see what's going on.

**Comment by elizabethsrobert** [comment]
Thank you for the heads up. All files that were initially ".SKP" are now ".skp." If you have any further issues just let me know. 😄
