### ISSUE TITLE
QFN24-3X3.skp has incorrect dimensions

### ISSUE THREAD

**Issue by follower** [sparkfun/3D_Models#235]
The `QFN24-3X3.skp` file found in <https://github.com/sparkfun/3D_Models/blob/master/production_parts/semiconductors/IC_SMD/QFN/QFN-24/skp/> appears to have dimensions of 4x4mm (like the existing QFN24 files) rather than the correct dimensions of 3x3mm.

This can be observed in the SketchUp model of the Razor IMU:
![qfn24-3x3-incorrect-dimensions-issue](https://cloud.githubusercontent.com/assets/189962/22111602/b8cc3a78-dec4-11e6-9d6e-e5f970476d8a.png)

The screenshot shows the part overlapping the location dot and nearby via, when compared to the product photo: <https://www.sparkfun.com/products/14001>

**Comment by elizabethsrobert** [comment]
Thank you so much for all your help with this Repo. It's greatly appreciated! :smile:  

I fixed the sizing issue for [QFN24-3X3](https://github.com/sparkfun/3D_Models/tree/master/production_parts/semiconductors/IC_SMD/QFN/QFN-24) which should now be reflected on [Product 14001](https://github.com/sparkfun/3D_Models/tree/master/products/14001).

**Comment by follower** [comment]
Thanks for the dimension fix, looks good now.

My help is thanks to my client Omniblox, you might like to take a look at some of the final result here: http://omniblox.io/eagleloader/sparkfun-redstick

Thanks again for the fix.
