### ISSUE TITLE
.STL build error

### ISSUE THREAD

**Issue by cmfrancis** [sparkfun/3D_Models#257]
Customer reports the .STL had a build error. Can someone check on this and repair if needed?

**Comment by ToniCorinne** [comment]
@cmfrancis What .stl? We need more information to actually verify this is an issue.

**Comment by cmfrancis** [comment]
Sorry about that Toni. It's for product 12959.

https://github.com/sparkfun/3D_Models/blob/master/products/12959/stl/SparkFun_MOSFET_Power_Control_Kit.stl

**Comment by santaimpersonator** [comment]
The file seems fine now. Closing Issue.
